export const MAX_PRODUCT_QUANTITY_ALLOWED = 2;
export const PREPAID_ORDER_DELIVERY_CHARGE = 65;
export const COD_ORDER_DELIVERY_CHARGE = 160;
export const PREPAID_ORDER_THRESHOLD_FOR_FREE_DELIVERY = 500;
